service: youtube-bot-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  memorySize: 128
  timeout: 10
  environment:
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}

functions:
  botHandler:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /telegram-webhook
          method: post

plugins: []

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: "node18"
    platform: "node"
    outExtension:
      .js: .js

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "dist/**"

